name: Trufflehog Scan

on:
  push:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Trufflehog
        run: |
          pip install trufflehog
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.28.0
      - name: Scan for Secrets
        run: |
          trufflehog scan https://github.com/palakrawat-bct/spring-petclinic.git 

