name: Trufflehog Scan

on:
  push:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Trufflehog
        run: |
          pip install trufflehog
      - name: Scan for Secrets
        run: |
          trufflehog github --org=trufflesecurity --only-verified
