name: TruffleHog Scan

on:
  push:
    branches: [ main ]

jobs:
  trufflehog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: TruffleHog Scan
        uses: adrian-gheorghe/trufflehog-github-action@v2
        with:
          repo-path: "."
          sensitive-string-file-path: "sensitive-strings.txt"

