name: Trufflehog Scan

on:
  push:
    branches: [main]

jobs:
  trufflehog-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.28.0

      - name: Scan for Secrets
        run: |
          trufflehog git https://github.com/trufflesecurity/test_keys --only-verified
